#!/bin/bash

#Loetleme numbreid

sum=0

for (( nr = 1; nr < 11; nr++ )); do
	jk=$(($nr % 2))
	if [ $jk -eq 0 ]; then
		sum=$(($sum + $nr))
		echo $sum
	fi
done
echo "Vahemikus 1-10 on paarisarvude summa: $sum "
# lõpp

