#!/bin/bash

#Millisesse vanuserühma inimene kuulub.
#Kasutaja sisestus
echo -n "Sisesta oma vanus: "
read iga

vanus=$iga
#Kontrolli osa
if [ $vanus -gt 0 -a $vanus -lt 11 ]; then
	echo "Sa oled laps"
elif [ $vanus -ge 11 -a $vanus -lt 18 ]; then
	echo "Sa oled nooruk"
elif [ $vanus -ge 18 -a $vanus -lt 63 ]; then
	echo "Sa oled täiskasvanu"
elif [ $vanus -ge 63 ]; then
	echo "Sa oled seenior"
#Vigase sisestuse korral
else
	echo "Vigane sisestus!"
fi
