#!/bin/bash
#Aastaajad
echo -n "Sisesta kuu number: "
read kuu

if [ $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 ]; then
	echo "Praegu on talv ja loodetavasti lumi"
elif [ $kuu -ge 3 -a $kuu -le 5 ]; then
	echo "Praegu on kevad ja värskus"
elif [ $kuu -ge 6 -a $kuu -le 8 ]; then
	echo "Praegu on suvi ja päike"
elif [ $kuu -ge 9 -a $kuu -le 11 ]; then
	echo "Praegu on sügis ja sopane"
else
	echo "Antud numbriga kuud pole. Vähemalt selles kalendris."
fi


