#!/bin/bash

#Paaris või paaritu

echo -n "Sisesta suvaline täisarv: "
read arv

arv2=$(($arv % 2))

#On oluline panna tingimuslausele mõlemale poole tühikud enne kandilisi sulge.

if [ $arv2 -eq 0 ]
then
	echo "$arv on paaris"
else
	echo "$arv on paaritu"
fi

